# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TTs.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import pyttsx3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 579)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(66, 66, 66);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Rock Salt")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.TextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.TextBox.setGeometry(QtCore.QRect(170, 60, 591, 461))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.TextBox.setFont(font)
        self.TextBox.setObjectName("TextBox")
        self.Convert = QtWidgets.QPushButton(self.centralwidget)
        self.Convert.setGeometry(QtCore.QRect(20, 80, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.Convert.setFont(font)
        self.Convert.setStyleSheet("background-color: rgb(255, 60, 12);")
        self.Convert.setObjectName("Convert")
        self.Clear = QtWidgets.QPushButton(self.centralwidget)
        self.Clear.setGeometry(QtCore.QRect(20, 190, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.Clear.setFont(font)
        self.Clear.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.Clear.setObjectName("Clear")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 280, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.volumeAdjuster = QtWidgets.QSlider(self.centralwidget)
        self.volumeAdjuster.setGeometry(QtCore.QRect(20, 330, 131, 22))
        self.volumeAdjuster.setOrientation(QtCore.Qt.Horizontal)
        self.volumeAdjuster.setObjectName("volumeAdjuster")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 21))
        self.menubar.setObjectName("menubar")
        self.menuTTS = QtWidgets.QMenu(self.menubar)
        self.menuTTS.setObjectName("menuTTS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTTS.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Clear.clicked.connect(self.TTS_callBack)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate(
            "MainWindow", "Text To Speech Converter"))
        self.Convert.setText(_translate("MainWindow", "Convert"))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.label_2.setText(_translate("MainWindow", "Volume"))
        self.menuTTS.setTitle(_translate("MainWindow", "TTS"))

    def TTS_callBack(self):
        events = self.sender()
        engine = pyttsx3.init('sapi5')
        textLab = self.TextBox.text()
        if events.text() == 'Clear':
            self.TextBox.clear()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
