# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TTS.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyttsx3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: rgb(53, 53, 53);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(140, 10, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Android")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(200, 60, 591, 441))
        self.textEdit.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setStyleSheet("background-color: rgb(44, 44, 44);\n"
                                    "color: rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.Convert = QtWidgets.QPushButton(self.centralwidget)
        self.Convert.setGeometry(QtCore.QRect(10, 80, 161, 61))
        self.Convert.setMinimumSize(QtCore.QSize(161, 61))
        self.Convert.setMaximumSize(QtCore.QSize(161, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.Convert.setFont(font)
        self.Convert.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Convert.setStyleSheet("background-color: rgb(170, 255, 0);\n"
                                   "\n"
                                   "color: rgb(57, 57, 57);")
        self.Convert.setObjectName("Convert")
        self.erase = QtWidgets.QPushButton(self.centralwidget)
        self.erase.setGeometry(QtCore.QRect(10, 180, 161, 61))
        self.erase.setMinimumSize(QtCore.QSize(161, 61))
        self.erase.setMaximumSize(QtCore.QSize(161, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.erase.setFont(font)
        self.erase.setStyleSheet("background-color: rgb(170, 255, 0);\n"
                                 "\n"
                                 "color: rgb(57, 57, 57);")
        self.erase.setObjectName("erase")
        self.subHeading = QtWidgets.QLabel(self.centralwidget)
        self.subHeading.setGeometry(QtCore.QRect(20, 270, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.subHeading.setFont(font)
        self.subHeading.setObjectName("subHeading")
        self.volumeAdjuster = QtWidgets.QSlider(self.centralwidget)
        self.volumeAdjuster.setGeometry(QtCore.QRect(10, 330, 160, 22))
        self.volumeAdjuster.setMinimumSize(QtCore.QSize(160, 22))
        self.volumeAdjuster.setMaximumSize(QtCore.QSize(160, 22))
        self.volumeAdjuster.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.volumeAdjuster.setMaximum(30)
        self.volumeAdjuster.setPageStep(2)
        self.volumeAdjuster.setSliderPosition(5)
        self.volumeAdjuster.setOrientation(QtCore.Qt.Horizontal)
        self.volumeAdjuster.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.volumeAdjuster.setTickInterval(5)
        self.volumeAdjuster.setObjectName("volumeAdjuster")
        self.subHeading_2 = QtWidgets.QLabel(self.centralwidget)
        self.subHeading_2.setGeometry(QtCore.QRect(10, 380, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(20)
        self.subHeading_2.setFont(font)
        self.subHeading_2.setObjectName("subHeading_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(10, 440, 82, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        self.radioButton.setFont(font)
        self.radioButton.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 470, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(16)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.radioButton_2.setObjectName("radioButton_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(410, 520, 371, 31))
        self.progressBar.setMinimumSize(QtCore.QSize(371, 31))
        self.progressBar.setMaximumSize(QtCore.QSize(371, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.subHeading_3 = QtWidgets.QLabel(self.centralwidget)
        self.subHeading_3.setGeometry(QtCore.QRect(300, 510, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(18)
        self.subHeading_3.setFont(font)
        self.subHeading_3.setObjectName("subHeading_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.erase.clicked.connect(self.clearALL)
        self.Convert.clicked.connect(self.TTS_Converter)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate(
            "MainWindow", "Text To Speech Converter"))
        self.textEdit.setStatusTip(_translate(
            "MainWindow", "Enter Your Text Here ............"))
        self.Convert.setStatusTip(_translate(
            "MainWindow", "Convert The Text into Speech..!!"))
        self.Convert.setText(_translate("MainWindow", "Convert"))
        self.Convert.setShortcut(_translate("MainWindow", "Alt+Shift+C"))
        self.erase.setStatusTip(_translate(
            "MainWindow", "Erase All The Text !!"))
        self.erase.setText(_translate("MainWindow", "Clear All"))
        self.erase.setShortcut(_translate("MainWindow", "Alt+E"))
        self.subHeading.setText(_translate("MainWindow", "Volume"))
        self.volumeAdjuster.setStatusTip(
            _translate("MainWindow", "Adjust the volume"))
        self.subHeading_2.setText(_translate("MainWindow", "Voice"))
        self.radioButton.setStatusTip(_translate("MainWindow", "Male Voice"))
        self.radioButton.setText(_translate("MainWindow", "Male"))
        self.radioButton_2.setStatusTip(
            _translate("MainWindow", "female Voice"))
        self.radioButton_2.setText(_translate("MainWindow", "Female"))
        self.progressBar.setStatusTip(_translate("MainWindow", "Read Status"))
        self.subHeading_3.setStatusTip(_translate("MainWindow", "Read Status"))
        self.subHeading_3.setText(_translate("MainWindow", "Progress"))

    def clearALL(self):
        self.textEdit.clear()

    def TTS_Converter(self):
        engine = pyttsx3.init('sapi5')
        txt = self.textEdit.toPlainText()
        engine.say(txt)
        engine.runAndWait()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
